// ============================================================
// WHITE HOUSE WEALTH OS — Mock/Demo Data
// ============================================================

import type {
  DashboardData,
  WealthData,
  Transaction,
  FIREData,
  ScenarioResult,
  ChatMessage,
  Conversation,
  SpendingTrend,
  Budget,
} from '@/types'

export const MOCK_DASHBOARD_DATA: DashboardData = {
  safe_to_spend: 2847,
  safe_to_spend_breakdown: {
    total_cash: 14320,
    upcoming_bills_7d: 3200,
    upcoming_bills_30d: 8100,
    buffer_reserve: 1500,
    sinking_fund_reserve: 2000,
  },
  total_liquid_cash: 14320,
  emergency_fund: {
    current: 18500,
    target: 24000,
    months_runway: 4.6,
    monthly_expenses: 4000,
  },
  accounts: [
    {
      id: 'acc_1',
      name: 'Primary Checking',
      type: 'checking',
      balance: 8420,
      institution: 'Chase Bank',
      color: '#3b82f6',
      icon: 'building',
      last_updated: '2026-05-25T08:00:00Z',
      account_number_last4: '4521',
    },
    {
      id: 'acc_2',
      name: 'High-Yield Savings',
      type: 'savings',
      balance: 18500,
      institution: 'Marcus by Goldman',
      color: '#10b981',
      icon: 'piggy-bank',
      last_updated: '2026-05-25T08:00:00Z',
      interest_rate: 5.1,
      account_number_last4: '7892',
    },
    {
      id: 'acc_3',
      name: 'Joint Checking',
      type: 'checking',
      balance: 3200,
      institution: 'Chase Bank',
      color: '#8b5cf6',
      icon: 'building',
      last_updated: '2026-05-25T08:00:00Z',
      account_number_last4: '3301',
    },
    {
      id: 'acc_4',
      name: 'Josh 401(k)',
      type: 'retirement',
      balance: 87400,
      institution: 'Fidelity',
      color: '#f59e0b',
      icon: 'chart-line',
      last_updated: '2026-05-24T00:00:00Z',
      account_number_last4: '6612',
    },
    {
      id: 'acc_5',
      name: 'Ashley 401(k)',
      type: 'retirement',
      balance: 52100,
      institution: 'Vanguard',
      color: '#ec4899',
      icon: 'chart-line',
      last_updated: '2026-05-24T00:00:00Z',
      account_number_last4: '9940',
    },
    {
      id: 'acc_6',
      name: 'Brokerage',
      type: 'investment',
      balance: 34200,
      institution: 'Fidelity',
      color: '#06b6d4',
      icon: 'trending-up',
      last_updated: '2026-05-25T16:00:00Z',
      account_number_last4: '2287',
    },
  ],
  debts: [
    {
      id: 'debt_1',
      name: 'Chase Sapphire',
      balance: 4250,
      apr: 24.99,
      min_payment: 85,
      monthly_payment: 400,
      institution: 'Chase',
      type: 'credit_card',
      color: '#ef4444',
    },
    {
      id: 'debt_2',
      name: 'Amazon Visa',
      balance: 2100,
      apr: 28.99,
      min_payment: 42,
      monthly_payment: 200,
      institution: 'Synchrony',
      type: 'credit_card',
      promo_expiry: '2026-12-01',
      promo_apr: 0,
      color: '#f97316',
    },
    {
      id: 'debt_3',
      name: 'Ford F-150 Loan',
      balance: 18400,
      apr: 6.9,
      min_payment: 387,
      monthly_payment: 387,
      institution: 'Ford Credit',
      type: 'auto_loan',
      color: '#3b82f6',
    },
    {
      id: 'debt_4',
      name: 'Home Mortgage',
      balance: 224000,
      apr: 6.25,
      min_payment: 1650,
      monthly_payment: 1650,
      institution: 'Rocket Mortgage',
      type: 'mortgage',
      color: '#8b5cf6',
    },
  ],
  upcoming_bills: [
    {
      id: 'bill_1',
      name: 'Mortgage',
      amount: 1650,
      due_date: '2026-06-01',
      status: 'upcoming',
      category: 'Housing',
      auto_pay: true,
      icon: 'home',
    },
    {
      id: 'bill_2',
      name: 'Electric Bill',
      amount: 187,
      due_date: '2026-05-28',
      status: 'due',
      category: 'Utilities',
      auto_pay: false,
      icon: 'zap',
    },
    {
      id: 'bill_3',
      name: 'Internet',
      amount: 79,
      due_date: '2026-05-30',
      status: 'upcoming',
      category: 'Utilities',
      auto_pay: true,
      icon: 'wifi',
    },
    {
      id: 'bill_4',
      name: 'Car Insurance',
      amount: 247,
      due_date: '2026-06-03',
      status: 'upcoming',
      category: 'Insurance',
      auto_pay: true,
      icon: 'shield',
    },
    {
      id: 'bill_5',
      name: 'Netflix',
      amount: 22.99,
      due_date: '2026-05-27',
      status: 'due',
      category: 'Entertainment',
      auto_pay: true,
      icon: 'tv',
    },
    {
      id: 'bill_6',
      name: 'Gym Membership',
      amount: 45,
      due_date: '2026-06-01',
      status: 'upcoming',
      category: 'Health',
      auto_pay: true,
      icon: 'dumbbell',
    },
  ],
  sinking_funds: [
    {
      id: 'sf_1',
      name: 'Vacation Fund',
      current: 3200,
      target: 5000,
      monthly_contribution: 300,
      target_date: '2026-12-01',
      color: '#3b82f6',
      icon: 'plane',
    },
    {
      id: 'sf_2',
      name: 'Car Maintenance',
      current: 850,
      target: 1200,
      monthly_contribution: 100,
      color: '#f59e0b',
      icon: 'car',
    },
    {
      id: 'sf_3',
      name: 'Christmas',
      current: 600,
      target: 2000,
      monthly_contribution: 166,
      target_date: '2026-12-01',
      color: '#ef4444',
      icon: 'gift',
    },
    {
      id: 'sf_4',
      name: 'Home Repair',
      current: 1800,
      target: 3000,
      monthly_contribution: 200,
      color: '#10b981',
      icon: 'hammer',
    },
  ],
  weekly_priorities: [
    {
      id: 'wp_1',
      title: 'Pay Electric Bill',
      description: '$187 due May 28 — avoid late fee',
      urgency: 'high',
      type: 'action',
      amount: 187,
      deadline: '2026-05-28',
    },
    {
      id: 'wp_2',
      title: 'Amazon Promo Expires Dec 1',
      description: 'Pay $2,100 balance before interest kicks in',
      urgency: 'high',
      type: 'alert',
      amount: 2100,
      deadline: '2026-12-01',
    },
    {
      id: 'wp_3',
      title: 'Boost Emergency Fund',
      description: 'You\'re at 4.6 months — target is 6 months',
      urgency: 'medium',
      type: 'opportunity',
      amount: 5500,
    },
    {
      id: 'wp_4',
      title: 'Chase Sapphire Payoff',
      description: 'At current rate, paid off in ~11 months',
      urgency: 'medium',
      type: 'reminder',
      amount: 4250,
    },
  ],
  hermes_briefing:
    'Good morning! Your safe-to-spend is **$2,847** this week. Your electric bill of $187 is due Thursday — I\'ve flagged it as your top priority. Your Amazon Visa promo rate expires December 1st; consider putting your upcoming tax refund toward that balance to save ~$680 in interest. Your emergency fund is at 4.6 months — a solid position, but boosting to 6 months would qualify you to start investing more aggressively. Net worth is up $1,240 this month.',
  monthly_forecast: Array.from({ length: 90 }, (_, i) => {
    const date = new Date('2026-05-25')
    date.setDate(date.getDate() + i)
    const baseBalance = 14320
    const dailyIncome = i % 14 === 0 ? 5200 : 0
    const dailyExpense = 150 + Math.random() * 50
    const balance30 = baseBalance + dailyIncome * Math.floor(i / 14) - dailyExpense * i
    return {
      date: date.toISOString().split('T')[0],
      balance_30: Math.max(0, balance30),
      balance_60: Math.max(0, balance30 * 0.95),
      balance_90: Math.max(0, balance30 * 0.9),
    }
  }),
  net_worth: 160450,
  total_assets: 403820,
  total_liabilities: 248750,
  last_updated: '2026-05-25T08:30:00Z',
}

export const MOCK_WEALTH_DATA: WealthData = {
  net_worth: 160450,
  net_worth_history: Array.from({ length: 13 }, (_, i) => {
    const date = new Date('2025-05-01')
    date.setMonth(date.getMonth() + i)
    const base = 145000
    const growth = i * 1200 + Math.random() * 800 - 200
    const assets = 385000 + growth * 2.5
    const liabilities = 252000 - i * 500
    return {
      date: date.toISOString().split('T')[0],
      net_worth: base + growth,
      assets,
      liabilities,
    }
  }),
  total_assets: 403820,
  total_liabilities: 248750,
  asset_allocation: [
    { name: 'Retirement', value: 139500, percentage: 34.5, color: '#f59e0b' },
    { name: 'Real Estate', value: 285000, percentage: 70.6, color: '#8b5cf6' },
    { name: 'Brokerage', value: 34200, percentage: 8.5, color: '#3b82f6' },
    { name: 'Cash', value: 29920, percentage: 7.4, color: '#10b981' },
  ],
  accounts: MOCK_DASHBOARD_DATA.accounts,
  debts: MOCK_DASHBOARD_DATA.debts,
  debt_by_category: [
    { name: 'Mortgage', total: 224000, count: 1, avg_apr: 6.25, color: '#8b5cf6' },
    { name: 'Auto Loan', total: 18400, count: 1, avg_apr: 6.9, color: '#3b82f6' },
    { name: 'Credit Cards', total: 6350, count: 2, avg_apr: 26.99, color: '#ef4444' },
  ],
}

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_1',
    date: '2026-05-25',
    amount: -127.43,
    description: 'Walmart Supercenter',
    merchant_name: 'Walmart',
    category: 'Groceries',
    type: 'debit',
    status: 'posted',
    account_id: 'acc_1',
    account_name: 'Primary Checking',
  },
  {
    id: 'tx_2',
    date: '2026-05-24',
    amount: 5200,
    description: 'ACH Deposit - Payroll',
    merchant_name: 'Employer Direct Deposit',
    category: 'Income',
    type: 'credit',
    status: 'posted',
    account_id: 'acc_1',
    account_name: 'Primary Checking',
  },
  {
    id: 'tx_3',
    date: '2026-05-24',
    amount: -48.32,
    description: 'Shell Gas Station',
    merchant_name: 'Shell',
    category: 'Gas & Fuel',
    type: 'debit',
    status: 'posted',
    account_id: 'acc_1',
    account_name: 'Primary Checking',
  },
  {
    id: 'tx_4',
    date: '2026-05-23',
    amount: -22.99,
    description: 'Netflix Subscription',
    merchant_name: 'Netflix',
    category: 'Entertainment',
    type: 'debit',
    status: 'posted',
    account_id: 'acc_3',
    account_name: 'Joint Checking',
  },
  {
    id: 'tx_5',
    date: '2026-05-23',
    amount: -156.80,
    description: 'Chick-fil-A, Taco Bell, Panera',
    merchant_name: 'Various Restaurants',
    category: 'Dining Out',
    type: 'debit',
    status: 'posted',
    account_id: 'acc_1',
    account_name: 'Primary Checking',
  },
  {
    id: 'tx_6',
    date: '2026-05-22',
    amount: -387,
    description: 'Ford Motor Credit',
    merchant_name: 'Ford Credit',
    category: 'Auto Payment',
    type: 'debit',
    status: 'posted',
    account_id: 'acc_1',
    account_name: 'Primary Checking',
  },
  {
    id: 'tx_7',
    date: '2026-05-21',
    amount: -245.10,
    description: 'Kroger',
    merchant_name: 'Kroger',
    category: 'Groceries',
    type: 'debit',
    status: 'posted',
    account_id: 'acc_3',
    account_name: 'Joint Checking',
  },
  {
    id: 'tx_8',
    date: '2026-05-20',
    amount: -1650,
    description: 'Rocket Mortgage - May Payment',
    merchant_name: 'Rocket Mortgage',
    category: 'Mortgage',
    type: 'debit',
    status: 'posted',
    account_id: 'acc_1',
    account_name: 'Primary Checking',
  },
  {
    id: 'tx_9',
    date: '2026-05-20',
    amount: -45,
    description: 'Planet Fitness',
    merchant_name: 'Planet Fitness',
    category: 'Health & Fitness',
    type: 'debit',
    status: 'posted',
    account_id: 'acc_3',
    account_name: 'Joint Checking',
  },
  {
    id: 'tx_10',
    date: '2026-05-19',
    amount: 4800,
    description: 'ACH Deposit - Payroll',
    merchant_name: 'Employer Direct Deposit',
    category: 'Income',
    type: 'credit',
    status: 'posted',
    account_id: 'acc_3',
    account_name: 'Joint Checking',
  },
  {
    id: 'tx_11',
    date: '2026-05-18',
    amount: -89.47,
    description: 'Amazon.com',
    merchant_name: 'Amazon',
    category: 'Shopping',
    type: 'debit',
    status: 'posted',
    account_id: 'acc_1',
    account_name: 'Primary Checking',
  },
  {
    id: 'tx_12',
    date: '2026-05-17',
    amount: -187,
    description: 'Evergy Electric',
    merchant_name: 'Evergy',
    category: 'Utilities',
    type: 'debit',
    status: 'pending',
    account_id: 'acc_1',
    account_name: 'Primary Checking',
  },
]

export const MOCK_BUDGETS: Budget[] = [
  { id: 'b_1', name: 'Groceries', amount: 800, spent: 372, period: 'monthly', category: 'Groceries', color: '#10b981' },
  { id: 'b_2', name: 'Dining Out', amount: 400, spent: 387, period: 'monthly', category: 'Dining Out', color: '#ef4444' },
  { id: 'b_3', name: 'Gas & Fuel', amount: 250, spent: 148, period: 'monthly', category: 'Gas & Fuel', color: '#3b82f6' },
  { id: 'b_4', name: 'Entertainment', amount: 150, spent: 68, period: 'monthly', category: 'Entertainment', color: '#8b5cf6' },
  { id: 'b_5', name: 'Shopping', amount: 300, spent: 267, period: 'monthly', category: 'Shopping', color: '#f59e0b' },
  { id: 'b_6', name: 'Health & Fitness', amount: 100, spent: 45, period: 'monthly', category: 'Health', color: '#06b6d4' },
  { id: 'b_7', name: 'Subscriptions', amount: 80, spent: 58, period: 'monthly', category: 'Subscriptions', color: '#ec4899' },
  { id: 'b_8', name: 'Kids Activities', amount: 200, spent: 120, period: 'monthly', category: 'Kids', color: '#f97316' },
]

export const MOCK_SPENDING_TRENDS: SpendingTrend[] = Array.from({ length: 6 }, (_, i) => {
  const date = new Date('2025-12-01')
  date.setMonth(date.getMonth() + i)
  return {
    month: date.toISOString().split('T')[0],
    total: 4200 + Math.random() * 800 - 400,
    by_category: {
      Groceries: 700 + Math.random() * 200,
      'Dining Out': 350 + Math.random() * 150,
      'Gas & Fuel': 200 + Math.random() * 100,
      Entertainment: 100 + Math.random() * 80,
      Shopping: 250 + Math.random() * 200,
    },
  }
})

export const MOCK_FIRE_DATA: FIREData = {
  fi_number: 2000000,
  fi_percentage: 31.2,
  current_savings: 175500,
  monthly_contribution: 2800,
  estimated_fi_date: '2042-03-01',
  years_to_fi: 16.3,
  fire_mode: 'fat',
  assumptions: {
    annual_expenses: 80000,
    swr: 4,
    expected_return: 7,
    inflation_rate: 3,
    social_security_age: 67,
    social_security_benefit: 2400,
    fire_age: 55,
    fire_mode: 'fat',
  },
  monte_carlo: Array.from({ length: 30 }, (_, i) => {
    const year = 2026 + i
    const base = 175500
    const annualContrib = 2800 * 12
    const growthRate = 0.07
    const t = i + 1
    const p50 = base * Math.pow(1 + growthRate, t) + annualContrib * ((Math.pow(1 + growthRate, t) - 1) / growthRate)
    return {
      year,
      p10: p50 * 0.55,
      p25: p50 * 0.75,
      p50,
      p75: p50 * 1.25,
      p90: p50 * 1.5,
      target: 2000000,
    }
  }),
  coast_fi_number: 800000,
  barista_fi_number: 1200000,
  lean_fi_number: 1250000,
  fat_fi_number: 2500000,
}

export const MOCK_SCENARIO_RESULT: ScenarioResult = {
  verdict: 'CAUTION',
  verdict_reason: 'Doable but will strain emergency fund below 4-month target',
  cash_impact: -6500,
  cash_impact_percent: -45.4,
  emergency_impact: {
    before_months: 4.6,
    after_months: 2.9,
    delta: -1.7,
  },
  debt_timeline_impact: {
    current_payoff_date: '2027-04-01',
    new_payoff_date: '2027-04-01',
    extra_interest: 0,
  },
  retirement_impact: {
    fi_date_before: '2042-03-01',
    fi_date_after: '2042-06-01',
    delta_months: 3,
  },
  warnings: [
    'Emergency fund drops below 3-month minimum',
    'Disney trip puts vacation sinking fund at $0',
    'Consider saving for 3 more months first',
  ],
  opportunities: [
    'Use tax refund to fund half the trip',
    'Book off-season for 20-30% savings',
  ],
  logic_trace: [
    {
      step: 1,
      label: 'Current Liquid Cash',
      calculation: '$8,420 (checking) + $3,200 (joint) + $3,200 (vacation fund)',
      result: '$14,820',
      impact: 'neutral',
    },
    {
      step: 2,
      label: 'Trip Total Cost',
      calculation: 'Flights $1,200 + Hotel $1,800 + Park Tickets $1,400 + Food/Misc $1,600 + Buffer $500',
      result: '-$6,500',
      impact: 'negative',
    },
    {
      step: 3,
      label: 'Remaining Cash After Trip',
      calculation: '$14,820 - $6,500',
      result: '$8,320',
      impact: 'neutral',
    },
    {
      step: 4,
      label: 'Emergency Fund Impact',
      calculation: '$18,500 stays intact — trip funded from checking/vacation fund',
      result: 'Emergency fund not impacted directly',
      impact: 'positive',
    },
    {
      step: 5,
      label: 'Safe-to-Spend After',
      calculation: '$8,320 - $5,600 (30-day bills) - $1,500 (buffer)',
      result: '$1,220 safe-to-spend',
      impact: 'negative',
      detail: 'Below comfortable $2,000 floor',
    },
    {
      step: 6,
      label: 'FIRE Impact',
      calculation: 'Pausing vacation fund for 3 months to rebuild ($300/mo)',
      result: '+3 months to FI date',
      impact: 'negative',
    },
  ],
}

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg_1',
    role: 'assistant',
    content:
      "Hello! I'm **Hermes**, your AI financial advisor. I have full visibility into your White House Wealth dashboard — accounts, budgets, debts, goals, and more.\n\nHow can I help you today? Here are some things I can help with:\n- Analyze your spending patterns\n- Model financial decisions\n- Optimize your debt payoff strategy\n- Review your progress toward FIRE\n- Answer any financial questions",
    created_at: '2026-05-25T08:00:00Z',
    suggested_follow_ups: [
      'What is my safe to spend?',
      'Review my debt situation',
      'Am I on track for FIRE?',
    ],
  },
  {
    id: 'msg_2',
    role: 'user',
    content: 'How much can I safely spend this week?',
    created_at: '2026-05-25T08:01:00Z',
  },
  {
    id: 'msg_3',
    role: 'assistant',
    content:
      "Based on your current financial picture, your **safe-to-spend is $2,847** this week.\n\nHere's how that breaks down:\n\n| Component | Amount |\n|-----------|--------|\n| Total liquid cash | $14,320 |\n| Bills due in 7 days | -$3,200 |\n| Bills due in 30 days | -$8,100 |\n| Buffer reserve | -$1,500 |\n| Sinking fund reserve | -$2,000 |\n| **Safe to spend** | **$2,847** |\n\n⚠️ **Watch out:** Your electric bill ($187) is due Thursday, May 28. Make sure to pay that before spending on discretionary items.\n\nWant me to walk through any upcoming large expenses?",
    created_at: '2026-05-25T08:01:15Z',
    suggested_follow_ups: [
      'What bills are due this week?',
      'How is my grocery budget?',
      "Can I afford a date night?",
    ],
  },
]

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_1',
    title: 'Weekly Financial Review',
    created_at: '2026-05-25T08:00:00Z',
    updated_at: '2026-05-25T08:05:00Z',
    message_count: 6,
    last_message: 'Your safe-to-spend is $2,847 this week...',
  },
  {
    id: 'conv_2',
    title: 'Disney Trip Planning',
    created_at: '2026-05-20T14:30:00Z',
    updated_at: '2026-05-20T15:10:00Z',
    message_count: 12,
    last_message: 'Based on the scenario analysis, I recommend waiting 3 months...',
  },
  {
    id: 'conv_3',
    title: 'FIRE Strategy Discussion',
    created_at: '2026-05-15T09:00:00Z',
    updated_at: '2026-05-15T10:30:00Z',
    message_count: 8,
    last_message: 'At your current savings rate, you would reach FI in approximately 16 years...',
  },
]
